### ISSUE TITLE
Base context already set

### ISSUE THREAD

**Issue by harifsp** [YarikSOffice/LanguageTest#5]
Hi YarikSOffice,

Thanks for the Library. 

I have already using attachBaseContext for Font's 

@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(base)); //for font's
        super.attachBaseContext(LocaleManager.setLocale(base));  //for language
    }

Could you please tell me how to use multiple attachBaseContext in same Activity?

Thanks in Advance.

**Comment by YarikSOffice** [comment]
Hi harifsp,

Try to use `createConfigurationContext` passing the context returned from `CalligraphyContextWrapper.wrap`. Another option is using `updateConfiguration` as described in the article https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758 .

**Comment by ejdev1488** [comment]
can i have a library?
