### ISSUE TITLE
Does not work with 'appcompat:1.1.0'

### ISSUE THREAD

**Issue by ValentinTaleb** [YarikSOffice/LanguageTest#6]
Everything works fine until you update appcompat from `implementation 'androidx.appcompat:appcompat:1.0.2'` to `implementation 'androidx.appcompat:appcompat:1.1.0`

How can we fix this problem?

(More information about this issue here: https://stackoverflow.com/questions/55265834/change-locale-not-work-after-migrate-to-androidx)

Thank you very much :)

**Comment by YarikSOffice** [comment]
Hi @ValentinTaleb
It would be helpful if you could provide a little more elaborate description.
1. What is the issue exactly?
2. What branch are you using? since there are 2 different approaches in the repository

**Comment by ValentinTaleb** [comment]
Hi,

Sorry I didn't give a lot of information.

If I run the **master** branch on my device, everything is working perfectly and the language change as expected when I press the button to change the language.

As soon as I update the appcompat library in build.gradle (from `implementation 'androidx.appcompat:appcompat:1.0.2'` to `implementation 'androidx.appcompat:appcompat:1.1.0`), the language does not change anymore when you press the same button :)

**Comment by YarikSOffice** [comment]
Hi @ValentinTaleb 
According to the stackoverflow post and other [issues](https://issuetracker.google.com/issues?q=attachBaseContext%20appcompat%201.1.0) on issuetracker.google.com, this is a bug related to the dark mode (happens on API 21-25).

Luckily, it's going to be [fixed](https://issuetracker.google.com/issues/140602653) in the upcoming versions of appcompat (1.2.0-alphaXX and 1.1.1).

In meanwhile, you can use the workaround suggested in the stackoverflow post or use another technique for language change presented in [this](https://github.com/YarikSOffice/LanguageTest/tree/ignore_deprecation) repository.

Thanks for your contribution!

**Comment by UriahShaulMandel** [comment]
If anyone encounters this issue, and is still waiting for 1.1.1 or 1.2.0, the following stackoverflow answer worked for me on 1.1.0 :
https://stackoverflow.com/a/61420643

**Comment by nicolabeghin** [comment]
FYI: `appcompat:1.2.0` has been released on August 19th 2020

https://developer.android.com/jetpack/androidx/releases/appcompat

Still cannot change language with versions > `1.2.0`, but here's some input about https://stackoverflow.com/a/58004553/2378095

**Comment by YarikSOffice** [comment]
According to my tests, the version `1.2.0` indeed fixes the issue for this sample project.

However, if you use `ContextWrapper` or `ContextThemeWrapper` you need to implement a workaround according to the link mentioned by @nicolabeghin.
